In [5]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/wine.csv', header=None)

print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6497 non-null   float64
 1   1       6497 non-null   float64
 2   2       6497 non-null   float64
 3   3       6497 non-null   float64
 4   4       6497 non-null   float64
 5   5       6497 non-null   float64
 6   6       6497 non-null   float64
 7   7       6497 non-null   float64
 8   8       6497 non-null   float64
 9   9       6497 non-null   float64
 10  10      6497 non-null   float64
 11  11      6497 non-null   int64
 12  12      6497 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 660.0 KB
None
                0            1            2            3            4   \
count  6497.000000  6497.000000  6497.000000  6497.000000  6497.000000
mean      7.215307     0.339666     0.318633     5.443235     0.056034
std       1.296434     0.164636     0.145318     4.757804     0.035034
min       3.800000     0.080000     0.000000     0.600000     0.009000
25%       6.400000     0.230000     0.250000     1.800000     0.038000
50%       7.000000     0.290000     0.310000     3.000000     0.047000
75%       7.700000     0.400000     0.390000     8.100000     0.065000
max      15.900000     1.580000     1.660000    65.800000     0.611000

                5            6            7            8            9   \
count  6497.000000  6497.000000  6497.000000  6497.000000  6497.000000
mean     30.525319   115.744574     0.994697     3.218501     0.531268
std      17.749400    56.521855     0.002999     0.160787     0.148806
min       1.000000     6.000000     0.987110     2.720000     0.220000
25%      17.000000    77.000000     0.992340     3.110000     0.430000
50%      29.000000   118.000000     0.994890     3.210000     0.510000
75%      41.000000   156.000000     0.996990     3.320000     0.600000
max     289.000000   440.000000     1.038980     4.010000     2.000000

                10           11           12
count  6497.000000  6497.000000  6497.000000
mean     10.491801     5.818378     0.246114
std       1.192712     0.873255     0.430779
min       8.000000     3.000000     0.000000
25%       9.500000     5.000000     0.000000
50%      10.300000     6.000000     0.000000
75%      11.300000     6.000000     0.000000
max      14.900000     9.000000     1.000000

In [2]:
x = df.iloc[:,0:12]
y = df.iloc[:,12]